### ISSUE TITLE
Lesson7-Secret-Content-Missing

### ISSUE THREAD

**Issue by zhaofeng-shu33** [hpc-carpentry/hpc-intro#119]
I find this lesson very helpful. It seems Lesson 7 misses how to protect own data ?
From my view, some users tend to set some directories to mod 777 for some reasons (misleading tutorial online, sharing data with other users etc.) It is dangerous in some cases especially some tokens are publicly readable (like ssh public key, github token etc.)

On the other hand, some users use weak password and it is a security problem for the whole HPC I think, especially when local root exploit is possible.

**Comment by psteinb** [comment]
I am not sure I understand what you want to say. Are you suggesting an addition to lesson 7?

**Comment by zhaofeng-shu33** [comment]
Indeed

**Comment by tkphd** [comment]
File permissions on a cluster resource are indeed important. While no cluster sets permissions to 777 *by default*, a number of misguided users likely set this so that other users can read data/code/binaries directly. As @zhaofeng-shu33 points out, this is poor practice, since sensitive information can leak -- esp. SSH private keys. This particular failure is not silent: if you attempt to SSH into a machine with over-permissive settings on `~/.ssh`, you'll get an error and the connection will fail as it is assumed insecure.

That being said, this lesson focuses on the individual user of a shared resource, and is meant to be introductory. My recommendation is to keep this in mind for future lessons (hpc-shell perhaps?), but to close this issue as out-of-scope.

**Comment by psteinb** [comment]
Agreed. @zhaofeng-shu33 thanks for pointing that out. Please reopen the issue at will.
