### ISSUE TITLE
alternatives to seqtk

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#160]
In Ep. 14, section "Installing software of our own," we build [seqtk](https://github.com/lh3/seqtk) on the landing pad, but don't actually use it for anything. This is fine, except that the build is not quite clean:

```bash
$ make
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
seqtk.c: In function ‘stk_comp’:
seqtk.c:400:16: warning: variable ‘lc’ set but not used [-Wunused-but-set-variable]
    int la, lb, lc, na, nb, nc, cnt[11];
                ^
```

That's fine -- I'll just submit an issue to fix this... [nope, lh3 has decided warnings don't matter](https://github.com/lh3/seqtk/issues/120).

If we're going to build arbitrary software for fun, let's at least give our traffic to someone who demonstrates skilled software carpentry. If finding an alternative is too much, let's cut this section out.

**Comment by psteinb** [comment]
on top, the use of `spackpm` comes to my mind immediately. I would only include content that is later exercised with. So for example, I would only go through compiling something if we later use that. So I support @tkphd here to remove this.

**Comment by tkphd** [comment]
[SpackPM](https://spack.io), as a way to "install" something exogenous?
I like the idea of using the modules we've just loaded to compile (or EZ-install) something. Since `spackpm` is not installed everywhere, I think a gcc or gfortran build is still the most general method of exercising the knowledge.

**Comment by ocaisa** [comment]
I'm an [EasyBuild](https://easybuild.readthedocs.io/en/latest/) maintainer so without any bias whatsoever I would always suggest EasyBuild over Spack...

Honestly though, I wouldn't even mention either tool, both are powerful but act mostly as black boxes and do a lot of clever things behind the scenes that may hide the reality of compiling codes

**Comment by psteinb** [comment]
Again, this takes the discussion back to where it started somewhat. If `seqtk` is not used in any fashion during any follow-up material or exercises, than I think there is no point to 
a) call gcc directly to build `seqtk` or
b) use HPC swiss army knives like `spackpm` or `easybuild` to install it.
I think this is the conceptual part that we have to work on, i.e. devising the lesson in a way so that the software to be installed is used for something. Alternatively, we could come up with a package for ourselves that people need to install, e.g. think the ominous `lolcow` example of singularity.

**Comment by tkphd** [comment]
All I'm hearing is "remove `seqtk`" :slightly_smiling_face: 
Replacing it with something learners can use would be a separate ticket, like #21 or https://github.com/hpc-carpentry/coordination/issues/2.
