### ISSUE TITLE
Ep 16, "ps" output username should be templated

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/hpc-intro#165]
In Episode 16, there's an example of using the "ps" command, with associated output.  This output appears to have an obsolete user-name, which at a minimum should be replaced by the templated user-name, but this varies between installations, so the really-right answer is to promote this to a snippet. This has the additional advantage that it makes it work the same way as the other command output blocks.

**Comment by tkphd** [comment]
Since the output of `ps` changes second-to-second, let alone site-to-site, I'm not in favor of making a snippet. Perhaps we can convert this to an exercise: run `ps` on the landing pad and see what people are doing... the "solution" could include the stale output with a comment like "you should see something like this (stale, outdated, but representative)."

**Comment by reid-a** [comment]
I was mostly alarmed by the inconsistency in the username, which is (now) pretty consistently used elsewhere in the lesson. At a minimum, a user on the system should expect to see some of their own processes, so even if it's not a snippet, it still should use the appropriate username.

**Comment by tkphd** [comment]
That, we can do :slightly_smiling_face:

**Comment by reid-a** [comment]
The username can be fixed here by just referring to the right config variable. This has now been done in the main repo. The ps output itself is sufficiently generic that a snippet is not required for the business.
