### ISSUE TITLE
Snippets - bestpractice

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#168]
I see that site specific files are created when it comes to snippets "ComputeCanada_Graham_slurm" , "EPCC_Cirrus_pbs" etc..is that the best practice. This is good as it will prevents conflicts using  site.snippets
_episodes/16-resources.md:{% include {{ site.snippets }}/16/stat_output.snip %}

My question is should I commit our site specific configs when submitting PRs or should I have them in .gitignore?

**Comment by tkphd** [comment]
Please include all your snippets in the PR. Excluding content from Git is a mistake, and including these files will help your fellow travelers find relevant things and port the lesson for their site if they have a similar config.

We could make the Snippets Library an external repository, managed through `git submodule`, if this gets out of hand. I don't think it's a problem, though, since it's all text.

**Comment by Sabryr** [comment]
OK, that makes sense.
