### ISSUE TITLE
MobaXterm or GitBash?

### ISSUE THREAD

**Issue by symulation** [hpc-carpentry/hpc-intro#20]
The current version of the login suggests that MobaXterm is used on Windows (or PuTTY).  This certainly gets the job done.  However, Software Carpentry uses GitBash.  I know that the reason for MobaXterm is at least partly historical (it had nano while GitBash didn't and so was adopted by Compute Canada) and now not relevant (Oliver Stueker added nano to GitBash).  

Would GitBash be a better option here so that:

1. We align with Software Carpentry.
2. Windows users get Git as a bonus.

?

**Comment by symulation** [comment]
MobaXterm does have some nice features.  We don't use them, but still.

Thing to do it likely add Git Bash and also a quick summarizing table of why/when people might want to choose one over the other.

**Comment by pdoehle** [comment]
Regardless of the choice, I would pick just one to use throughout the lesson. Presenting multiple options will ultimately distract from the intent of teaching new users the basics of logging into an HPC system. An instructor could say something along the lines of: "There are multiple options, and if you find your needs outgrow the tools we are discussing today, please contact us."

**Comment by ChristinaLK** [comment]
+1 to @pdoehle's suggestion

**Comment by tkphd** [comment]
The *shell-novice* lesson has a rather good [overview of terminal applications](http://swcarpentry.github.io/shell-novice/setup.html) for the three OSes. Git for Windows (umbrella project including `git-bash`) is preferred; Windows Subsystem for Linux is mentioned for advanced users, but not belabored. I think we should ~steal~ make derivative work from that page.

I'm afraid Cygwin is becoming passé, since Microsoft has begun committing to open source toolchains. What a time to be alive!

**Comment by psteinb** [comment]
Yeah, let’s recommend git-bash. Putty, WSL and mobaxterm deserve honorable mention as good alternative options.

**Comment by tkphd** [comment]
Oh good, already committed language to this effect in an upcoming PR :-)
