### ISSUE TITLE
Jekyll Liveserve for errors

### ISSUE THREAD

**Issue by HaoZeke** [hpc-carpentry/hpc-intro#201]
So it has been a while, but [hawkins](https://github.com/awood/hawkins) as it is now called, does recompile the site constantly, highlighting changes, which might help do tasks like this faster. We might also want to have a shell/make/something setup to do generic substitutions. For the wider carpentries as well, I'm planning to push for [cookiecutter](https://cookiecutter.readthedocs.io/) templates which might help in the long run.

**Comment by psteinb** [comment]
@ocaisa @tkphd can you please comment on this? I cannot oversee at this moment how beneficial using `hawkins` would be for us.

**Comment by ocaisa** [comment]
I don't think I know enough to evaluate this. From looking at cookiecutter just now, I can't see what added value it gives over the liquid templating we already use. It asks questions to complete the template, but our snippet library approach wouldn't map well to that since they're not single word responses, and if you have to do those already by hand then also doing the yaml config file (which is in the same directory) is not such a big deal.

For hawkins, it's also not really clear (to me) what extra value it brings, `make serve` already continuously recompiles the site. It's three years since there was a commit in that repo...are we sure it is being maintained?

I'm most definitely not an expert on ruby or Jekyll though, maybe @HaoZeke can detail a little more where the benefits are?

**Comment by tkphd** [comment]
The ideas and suggestions for alternative ways to build & maintain the site are appreciated, @HaoZeke! Here's my hot take.

When you're developing the site locally, you can run `make serve` to build the site; as you make edits, Jekyll automatically rebuilds the site. From what I can tell, the [Hawkins](https://github.com/awood/hawkins) plugin adds a hook to auto-refresh the browser you're viewing the site in, so you can see changes to the rendered site as soon as you save changes to the input files. It's a neat idea! Unfortunately, this plugin has not been updated in 3 years, and the projects it refers to as "see also" have all been deprecated. I believe the extra, questionable dependency is not worth the increment in convenience it offers. Press F5 in your browser tab.

[cookiecutter](https://cookiecutter.readthedocs.io/) appears to bring Jekyll/Liquid variables to files of all kinds. The [demo](https://cookiecutter.readthedocs.io/en/1.7.2/first_steps.html#your-first-cookiecutter) applies it to a Python script. Since we already have templating through Jekyll, I tend to agree with @ocaisa that this does not add value.

**Comment by HaoZeke** [comment]
Well, the hook is the main reason why I keep it around, but it is more robust to actually hit F5 I suppose ^_^. I do hate outdated things, so that's the end of that.

Cookiecutter is a bit better off than Jekyll Liquid templates, since with the question-answer mechanism, we can avoid having to use sed and friends to find and replace variables. It's a bit like a meta-templating setup before Jekyll. Consider the directory setup described here (https://link.getmailspring.com/link/6AD0F954-6252-42FA-BFBB-5E3DB9186A48@getmailspring.com/0?redirect=https%3A%2F%2Fcookiecutter.readthedocs.io%2Fen%2F1.7.2%2Fadvanced%2Fdirectories.html&recipient=cmVwbHkrQUJCQ1VUN0xKRVZaR1VOUUpLUk1XN1Y1SEVLSUJFVkJOSEhDUU5RVUNVQHJlcGx5LmdpdGh1Yi5jb20%3D).

**Comment by tkphd** [comment]
I'm not sure we would avoid using find-and-replace tools. The live demo showed what to do when changing a variable name or which layer of the nested variable arrays it belongs to. Whether the variable substitution is performed by Jekyll or Cookiecutter, if the variable name changes, you have to change it in all the files in the repository. `sed` is my tool of choice for that; other developers' preferences may vary, but switching templating mechanisms doesn't "solve" this "problem."

**Comment by HaoZeke** [comment]
So the basic idea is to consume a cookiecutter.json which compiles into liquid environments. That way we don't need to do search and replace so much as opening a json and modifying the keyword.

**Comment by tkphd** [comment]
At present, we're opening a YAML file to replace keywords. Adding a dependency so we can edit keywords in a JSON file instead does not strike me as adding value.

**Comment by HaoZeke** [comment]
Fair enough, ^_^
