### ISSUE TITLE
Spelling convention

### ISSUE THREAD

**Issue by wirawan0** [hpc-carpentry/hpc-intro#237]
Hi folks, some of us reside in the U.S. and some others in Europe and other parts of the world. Which spelling of words should we agree upon? "color" or "colour"; "realize" or "realise"? Do you have thoughts? Can we consult what the Carpentries' convention is and follow the same?

**Comment by tkphd** [comment]
Per The Carpentries, there is no strict spelling convention: <https://github.com/carpentries/lesson-example/issues/231>. Since much of the material in this lesson was developed by European and Canadian team members, non-US spellings were adopted; much of the early work I did to homogenize language was done using the British English dictionary (`en_GB`). In code snippets local to your resource, use whatever you like.

**Comment by ChristinaLK** [comment]
There is technically a style guide: https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html

I don't know if this answers Wirawan's question though.

**Comment by wirawan0** [comment]
Turns out the style guide says it explicitly --

> "To ensure that the style guide is as widely applicable as possible, UK English spellings and usage will be used in favour of American spelling."

So there you have it... let us stick with `en_GB`.

**Comment by tkphd** [comment]
I parse that clause to mean the *Style Guide itself* will use `en_GB`, but in the interests of settling the question, yes, `en_GB` sounds good to me for our lessons as well.
