### ISSUE TITLE
cpus: sockets, cores, and threads

### ISSUE THREAD

**Issue by baberlevi** [hpc-carpentry/hpc-intro#60]
12-cluster talks about components and equates the terms CPUs, processors, and cores.  It doesn't make a distinction between sockets, cores, or threads for SMT (hyperthreading).  It seems like we should get that straight up front before the wrong understanding is cemented.

**Comment by ChristinaLK** [comment]
Remember the audience for this course is (possibly) a researcher who has never touched the command line and only has a hazy idea of what a processor/etc. is.  I'd rather spend time helping them understand what a program running in parallel means and what it looks like in practice than drilling down into these distinctions of hardware.  If that means dropping some terms because we're not able to explain them fully, I'd be okay with that.

**Comment by psteinb** [comment]
I am fully on board with @ChristinaLK. the topic of sockets-cores-threads is for sure important, but not essential for this course. I am closing this issue then. Please reopen if you think more discussion is needed. Thanks.
